services:
  web:
    container_name: web
    build: .
    volumes:
      - .:/opt/app/
    ports:
      - '8000:8000'
    env_file:
      - ./env/django.env
    links:
      - db

  db:
    container_name: db
    image: "postgres:14"
    ports:
      - "5432:5432"
    env_file:
      - ./env/postgres.env