services:
  web:
    container_name: web
    build: .
    volumes:
      - .:/opt/app/
    ports:
      - '8000'
    env_file:
      - ./env/django.env
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    container_name: postgres
    image: "postgres:14"
    ports:
      - '5432'
    env_file:
      - ./env/postgres.env