pid /run/nginx.pid;
error_log /var/log/nginx/error.log;

events {
        worker_connections 2048;
}

http {

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    tcp_nopush on;

    gzip on;
    gzip_min_length 1024;
    gzip_comp_level 6;
    gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;
    gzip_vary on;

    access_log /var/log/nginx/access.log;

    proxy_cache_path /opt/cache keys_zone=my_cache:10m max_size=1g inactive=60m;

    upstream ask-leykhner {
        server ask-leykhner:8000;
    }

    server {
        listen 80;

        client_max_body_size 100M;

        location ^~ /uploads/ {
            alias /opt/app/uploads/;
            try_files $uri $uri/ =404;
            access_log off;
            expires max;
            add_header Cache-Control "public";
        }

        location ^~ /static/ {
            alias /opt/app/static/;
            try_files $uri $uri/ =404;
            access_log off;
            expires max;
            add_header Cache-Control "public";
        }

#         location ~* \.[^/]+$ {
#             alias /opt/app/static;
#             access_log off;
#             expires max;
#             add_header Cache-Control "public";
#         }

        location / {
#########  Закомментировать следующие строки, чтобы отключить proxy_cache
            proxy_cache my_cache;
            proxy_cache_key $scheme$proxy_host$request_uri;
            proxy_cache_valid 200 302 10m;
            proxy_cache_valid 404 1m;
            proxy_ignore_headers Vary;
            proxy_cache_bypass $cookie_sessionid;
            add_header X-Cache-Status $upstream_cache_status;
##

            proxy_pass http://ask-leykhner;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}